import os
import structlog

logger = structlog.get_logger(__name__)


class EmailNotifier:
    """Dispatches GRC alert emails via SMTP."""

    def __init__(self) -> None:
        self.smtp_host = os.getenv("SMTP_HOST", "")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.smtp_user = os.getenv("SMTP_USER", "")
        self.smtp_pass = os.getenv("SMTP_PASS", "")
        self.to_email = os.getenv("ALERT_TO_EMAIL", "")

    async def send_alert(self, metric_id: str, metric_name: str, rag_status: str, message: str) -> bool:
        if not self.smtp_host or not self.to_email:
            logger.debug("email_alert_skipped_smtp_unconfigured")
            return False

        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"🚨 GRC Dashboard Alert: {metric_name} is {rag_status.upper()}"
        msg["From"] = self.smtp_user or "valence@grc.internal"
        msg["To"] = self.to_email

        html = f"""
        <html>
          <body style="font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px; color: #333;">
            <div style="background-color: #ffffff; padding: 20px; border-radius: 8px; border: 1px solid #ddd; max-width: 600px;">
              <h2 style="color: #ef4444;">🔮 VALENCE GRC Alert</h2>
              <p>An enterprise security metric SLA threshold breach has been detected.</p>
              <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
                <tr style="background-color: #f3f3f3;">
                  <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">Metric ID</td>
                  <td style="padding: 10px; border: 1px solid #ddd;">{metric_id}</td>
                </tr>
                <tr>
                  <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">Metric Name</td>
                  <td style="padding: 10px; border: 1px solid #ddd;">{metric_name}</td>
                </tr>
                <tr style="background-color: #f3f3f3;">
                  <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">RAG Status</td>
                  <td style="padding: 10px; border: 1px solid #ddd; color: #ef4444; font-weight: bold;">{rag_status}</td>
                </tr>
                <tr>
                  <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">Details</td>
                  <td style="padding: 10px; border: 1px solid #ddd;">{message}</td>
                </tr>
              </table>
              <div style="margin-top: 20px; font-size: 11px; color: #888;">
                This is an automated alert generated by the VALENCE quantitative risk quantification platform.
              </div>
            </div>
          </body>
        </html>
        """
        msg.attach(MIMEText(html, "html"))

        try:
            import aiosmtplib
            await aiosmtplib.send(
                msg,
                hostname=self.smtp_host,
                port=self.smtp_port,
                username=self.smtp_user,
                password=self.smtp_pass,
                use_tls=(self.smtp_port == 465),
                start_tls=(self.smtp_port == 587),
            )
            logger.info("email_alert_delivered", metric_id=metric_id)
            return True
        except ImportError:
            logger.warning("email_send_failed_aiosmtplib_missing")
            return False
        except Exception as e:
            logger.error("email_alert_exception", error=str(e))
            return False
