"""Scheduled auditor report exports — SOC 2 in 14 days delivery loop."""
from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import structlog
from sqlalchemy import select

from grc_dashboard.alerting.email_delivery import EmailDelivery
from grc_dashboard.db.models import ReportRecord, ReportSchedule
from grc_dashboard.db.persistence import get_report, save_report, update_report_status
from grc_dashboard.db.session import AsyncSessionLocal

logger = structlog.get_logger(__name__)

FREQUENCY_DELTAS = {
    "daily": timedelta(days=1),
    "weekly": timedelta(days=7),
    "monthly": timedelta(days=30),
}


def compute_next_run(frequency: str, from_time: datetime | None = None) -> datetime:
    base = from_time or datetime.now(UTC)
    delta = FREQUENCY_DELTAS.get(frequency, FREQUENCY_DELTAS["weekly"])
    return base + delta


async def list_schedules(session, tenant_id: str) -> list[dict[str, Any]]:
    result = await session.execute(
        select(ReportSchedule)
        .where(ReportSchedule.tenant_id == tenant_id)
        .order_by(ReportSchedule.created_at.desc())
    )
    return [
        {
            "id": row.id,
            "frequency": row.frequency,
            "framework": row.framework,
            "recipient_email": row.recipient_email,
            "enabled": row.enabled,
            "last_run_at": row.last_run_at.isoformat() if row.last_run_at else None,
            "next_run_at": row.next_run_at.isoformat() if row.next_run_at else None,
            "created_by": row.created_by,
        }
        for row in result.scalars().all()
    ]


async def process_due_schedules(state: Any) -> None:
    now = datetime.now(UTC)
    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(ReportSchedule).where(
                ReportSchedule.enabled.is_(True),
                ReportSchedule.next_run_at.is_not(None),
                ReportSchedule.next_run_at <= now,
            )
        )
        schedules = result.scalars().all()
        for schedule in schedules:
            await _run_scheduled_export(session, schedule, state)
            schedule.last_run_at = now
            schedule.next_run_at = compute_next_run(schedule.frequency, now)
        if schedules:
            await session.commit()


async def _run_scheduled_export(session, schedule: ReportSchedule, state: Any) -> None:
    tenant_id = schedule.tenant_id
    by_tenant: dict[str, Any] = getattr(state, "latest_results_by_tenant", {})
    results = by_tenant.get(tenant_id, {})
    run_id = results.get("run_id") or f"VALENCE_{uuid.uuid4().hex[:8].upper()}"

    record = ReportRecord(
        tenant_id=tenant_id,
        run_id=run_id,
        generated_at=datetime.now(UTC),
        generated_by=f"schedule:{schedule.created_by}",
        pdf_path="",
        snapshot_hash="",
        threshold_hash="",
        metric_count=len(results.get("metrics", [])),
        status="generating",
    )
    await save_report(session, record)

    from grc_dashboard.api.routers.reports import _generate_pdf_task

    await _generate_pdf_task(tenant_id, run_id)

    if schedule.recipient_email:
        async with AsyncSessionLocal() as mail_session:
            row = await get_report(mail_session, tenant_id, f"RPT_{run_id}")
            if row and row.status == "completed" and row.pdf_path:
                mailer = EmailDelivery()
                subject = f"VALENCE {schedule.framework} Auditor Export — {datetime.now(UTC).strftime('%Y-%m-%d')}"
                html = (
                    f"<p>Your scheduled <strong>{schedule.framework}</strong> compliance export is attached.</p>"
                    f"<p>Run ID: <code>{run_id}</code></p>"
                    f"<p>Generated by VALENCE GRC scheduled delivery.</p>"
                )
                sent = await mailer.send_report_email(
                    schedule.recipient_email,
                    subject,
                    html,
                    Path(row.pdf_path),
                )
                logger.info(
                    "scheduled_report_email",
                    tenant_id=tenant_id,
                    framework=schedule.framework,
                    recipient=schedule.recipient_email,
                    run_id=run_id,
                    delivered=sent,
                )
            else:
                logger.warning(
                    "scheduled_report_email_skipped",
                    tenant_id=tenant_id,
                    run_id=run_id,
                    reason="report_not_ready",
                )


async def run_report_scheduler(state: Any, interval_seconds: int = 3600) -> None:
    import asyncio

    while True:
        await asyncio.sleep(interval_seconds)
        try:
            await process_due_schedules(state)
        except Exception as exc:
            logger.error("report_scheduler_failed", error=str(exc))
